### PR TITLE
Support TLS connections to MQTT server

### PR DESCRIPTION
**Pull request by andreasbrett**
Added support for TLS connection to the MQTT server. Configuration through 2 settings:

- Verify TLS connection by checking if MQTT server's certificate is signed by one of the CA certificates provided in the path **MQTT_TLS_CACERTS**
- If **MQTT_TLS_INSECURE** is set to **True** server name will not be checked against host name provided in server certificate (caution, as the name suggests this is insecure! only use in non-production environments)

### CODE REVIEW

**Comment by lolouk44** [comment]
Thanks for your PR.
I've had a quick look and can't see anything that would break at first glance.
That being said I don't use TLS now, never have before either, and unfortunately don't have time to set something up for testing right now.
I can publish a beta version of the repo and docker container if you can test and feedback on the TLS side?
I'll test on the non TLS with your version.
How does that sound

**Comment by andreasbrett** [comment]
Yes, I can test this end of this week (Mi Scale is still in delivery).

**Review by lolouk44 — APPROVED** [review]

**Comment by lolouk44** [comment]
0.1.15a published.
Make sure you use the `0.1.15a` tag in your docker-compose, not `latest`

**Comment by andreasbrett** [comment]
Tested and working! I did find a bug though with the default of MQTT_DISCOVERY, I'll create a separate PR for that.

I also checked if the retain=false works and it did.
https://github.com/lolouk44/xiaomi_mi_scale/issues/44

**Pull request merged**
